name: Docker Image CI for .NET Core 9

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core 9 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # 使用 .NET Core 9 SDK

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test

    - name: Publish project
      run: dotnet publish -c Release -o ./publish

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Push Docker image
      run: docker push my-image-name:$(date +%s)
